language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"

notifications:
  email:
    on_success: never
    on_failure: never

script:
  - npm run test:travis
